### ISSUE TITLE
Templated Card won't load inside Conditional Card when Update All is pressed

### ISSUE THREAD

**Issue by bravesfan171** [daredoes/linked-lovelace-ui#10]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
1.3.1
**Last working release (if known):**
N/A
**Browser and Operating System:**
Chrome MacOS

**Description of problem:**
Really excited by this plugin! I am attempting to setup room cards that I can use in both my desktop and mobile dashboards that stay synced up via the template I made in my templates dashboard. I can get them to load perfectly fine on their own and in vertical stacks, but not in a Conditional card for some reason. The Template card with the Update All shows up but nothing happens after clicking it and refreshing.

Card:
```
type: conditional
conditions:
  - entity: input_select.dashboard_view
    state: Living Room
card:
  type: custom:linked-lovelace-template
  template: living-room
```
View:
```
template: true
views:
  - theme: Backend-selected
    title: Living Room
    path: living-room
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: Living Room
          - type: custom:mushroom-chips-card
            chips:
              - type: entity
                entity: sensor.downstairs_temperature
                icon_color: red
              - type: entity
                entity: binary_sensor.garage_door
                icon_color: green
              - type: entity
                entity: binary_sensor.living_room_windows
                icon_color: green
              - type: template
                icon: mdi:battery
                tap_action:
                  action: fire-dom-event
                  browser_mod:
                    service: browser_mod.popup
                    data:
                      content:
                        type: custom:auto-entities
                        card:
                          type: entities
                          title: Battery Levels
                          state_color: false
                        filter:
                          include:
                            - domain: sensor
                              name: '* [Bb]attery'
                              area: living_room
                              options:
                                secondary_info: last-changed
                          exclude:
                            - state: None
                        sort:
                          method: state
                          reverse: false
                          numeric: true
                  target: {}
                content: Batteries
          - type: custom:themable-grid
            cards:
              - type: tile
                entity: cover.living_room_blinds
                icon_tap_action:
                  action: toggle
                name: Blinds
              - type: tile
                entity: media_player.living_room_tv
                name: TV
                icon_tap_action:
                  action: toggle
              - type: tile
                entity: fan.living_room_fan
                name: Fan
                icon_tap_action:
                  action: toggle
              - type: tile
                entity: fan.living_room_air_purifier
                name: Air Purifier
              - type: tile
                entity: light.floor_lamp
                icon_tap_action:
                  action: toggle
                features:
                  - type: light-brightness
              - type: tile
                entity: light.table_lamp
                icon_tap_action:
                  action: toggle
                features:
                  - type: light-brightness
              - type: tile
                entity: light.wall_light
                icon_tap_action:
                  action: toggle
                features:
                  - type: light-brightness
              - type: tile
                entity: light.tv_light
                icon_tap_action:
                  action: toggle
                features:
                  - type: light-brightness
              - type: tile
                entity: light.garage_door_light
                icon_tap_action:
                  action: toggle
              - type: tile
                entity: light.living_room_fan
                icon_tap_action:
                  action: toggle
                name: Fan Light
              - type: tile
                entity: switch.fireplace
                icon_tap_action:
                  action: toggle
          - show_state: false
            show_name: false
            camera_view: live
            type: picture-entity
            entity: camera.living_room
            camera_image: camera.living_room
```

**Additional information:**
![Screenshot 2023-01-14 at 10 30 51 PM](https://user-images.githubusercontent.com/22349997/212521597-5493ff2c-6535-4c70-9018-43f01dec9cc2.jpg)
