### ISSUE TITLE
Views not updating

### ISSUE THREAD

**Issue by Mittlebenskrise** [daredoes/linked-lovelace-ui#12]
I have several views created using templates. Now I updated the template, but the view didn't change. If I try getting it set up again using the "basic" code as follows, the "Update All" button doesn't work.

```
type: custom:swipe-card
start_card: 1
cards:
  - type: horizontal-stack
    cards:
      - type: custom:linked-lovelace-template
        template: keller
      - type: custom:linked-lovelace-template
        template: erdgeschoss
  - type: horizontal-stack
    cards:
      - type: custom:linked-lovelace-template
        template: obergeschoss
      - type: custom:linked-lovelace-template
        template: dachgeschoss
```
