### ISSUE TITLE
Load in pop-ups?

### ISSUE THREAD

**Issue by The-Croz** [daredoes/linked-lovelace-ui#13]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
Latest
**Last working release (if known):**

**Browser and Operating System:**
Mac OS Chrome

**Description of problem:**
Is it possible to get the linked lovelace card working in pop-ups? I am trying to load a card in a browser mod pop-up but it just shows up with the refresh all card and won't load in.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by daredoes** [comment]
Could I get some screenshots? @The-Croz

**Comment by The-Croz** [comment]
![Untitled](https://user-images.githubusercontent.com/22349997/215511901-ff653734-7bd8-45f8-a5f7-965a6b529ad6.gif)
Here you go @daredoes this GIF should show you what's happening. The same card alongside the popup loads in fine, just not the card in the popup. Thanks for taking a look.

**Comment by daredoes** [comment]
Oh interesting. This is because I don't check that field for cards to render from templates. Should be pretty easy to add. Could you send me the YAML for that browser pop-up card?  @The-Croz

**Comment by The-Croz** [comment]
@daredoes sure thing. Here is the yaml:
```
show_name: true
show_icon: true
type: button
entity: input_button.dummy
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: ' '
      content:
        type: custom:linked-lovelace-template
        template: living-room
        template_data: {}
```
Thanks!
