### ISSUE TITLE
Update of templates scrambles styles of custom:button-card

### ISSUE THREAD

**Issue by NODeeJay** [daredoes/linked-lovelace-ui#28]
**Checklist:**

- [ x ] I updated to the latest version available
- [ x ] I cleared the cache of my browser
- [ x ] I removed the plugin, restarted home assistant, cleared the cache and added the plugin again

**Release with the issue:** 2.0.0-beta

**Last working release (if known):** N/A

**Browser and Operating System:** Windows 10 LTSC 1809, Android 12 on Vivo, 12 on Titan Slim & 10 on Umax 8"
From my tests I would assume it is browser and OS independent

**Description of problem:**
I have a horizontal stack with 3 cards. Left and right I have `custom:button-card` with no content but 50px width to adjust the `picture-elements` card that uses `ll_template`:
```
type: horizontal-stack
cards:
  - type: custom:button-card
    color_type: blank-card
    styles:
      card:
        - width: 50px
  - ll_template: map_compressed
    type: picture-elements
    image: https://homeassistant.local:8443/local/pic.png/
    elements:
      - type: state-badge
        entity: person.alex
        style:
          color: transparent
          '--label-badge-red': darkviolet
          top: 11%
          left: 7%
          transform: translate(-50%, -50%) scale(0.8, 0.8)
  - type: custom:button-card
    color_type: blank-card
    styles:
      card:
        - width: 50px
```

When I press UPDATE ALL on the `type: custom:linked-lovelace-template` card and refresh the dashboard, the templates are refreshed correctly, however, additionally, the custom:button-cards get corrupted and end up in:

```
type: custom:button-card
color_type: blank-card
styles:
  card:
    '0':
      width: 50px
```
the dash and the space are replaced by **'0':**

I can fix the cards but as soon as I update all templates those button-card styles get messed up.

**Javascript errors shown in the web inspector (if applicable):** N/A

**Additional information:** N/A
