### ISSUE TITLE
The context gets replicated after update

### ISSUE THREAD

**Issue by erkr** [daredoes/linked-lovelace-ui#40]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
2.2.5
**Last working release (if known):**

**Browser and Operating System:**
iOS Safari

**Description of problem:**

I create a collapsible card with sub cards. At the top level I defined a context.
After update, the context gets copied to all sub card levels. 
That should NOT happen. I even have another card where this doesn't happen. 3 examples included below.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

The original ll_key card, as I originally created:
``` 
ll_key: test_card
ll_context:
  group: sensor.temperatures_koelkasten
  name: Temperatuur
type: custom:collapsable-cards
title_card:
  type: tile
  name: <%= context.name %>
  entity: <%= context.group %>
cards:
  - type: custom:auto-entities
    card:
      type: entities
    filter:
      template: >
        {% set ns=namespace(entries=[]) %}  {% set entities=state_attr('<%=
        context.group %>','entity_id') or [] %}  {%- for entity in entities -%}
          {%- set ns.entries=ns.entries+[{'entity': entity, }] -%}
        {%- endfor -%}   {{ ns.entries }}
    sort:
      method: none
  - type: custom:auto-entities
    card:
      type: history-graph
      hours_to_show: 48
    filter:
      template: >
        {% set ns=namespace(entries=[]) %}  {% set entities=state_attr('<%=
        context.group %>','entity_id') or [] %}  {%- for entity in entities -%}
          {%- set ns.entries=ns.entries+[{'entity': entity, }] -%}
        {%- endfor -%}   {{ ns.entries }}
    sort:
      method: none
``` 

The same card after update (contains copies of ll_context in the sub cards):
``` 
ll_key: test_card
ll_context:
  group: sensor.temperatures_koelkasten
  name: Temperatuur
type: custom:collapsable-cards
title_card:
  type: tile
  name: <%= context.name %>
  entity: <%= context.group %>
cards:
  - type: custom:auto-entities
    card:
      type: entities
      ll_context:
        group: sensor.temperatures_koelkasten
        name: Temperatuur
    filter:
      template: >
        {% set ns=namespace(entries=[]) %}  {% set entities=state_attr('<%=
        context.group %>','entity_id') or [] %}  {%- for entity in entities -%}
          {%- set ns.entries=ns.entries+[{'entity': entity, }] -%}
        {%- endfor -%}   {{ ns.entries }}
    sort:
      method: none
    ll_context:
      group: sensor.temperatures_koelkasten
      name: Temperatuur
  - type: custom:auto-entities
    card:
      type: history-graph
      hours_to_show: 48
      ll_context:
        group: sensor.temperatures_koelkasten
        name: Temperatuur
    filter:
      template: >
        {% set ns=namespace(entries=[]) %}  {% set entities=state_attr('<%=
        context.group %>','entity_id') or [] %}  {%- for entity in entities -%}
          {%- set ns.entries=ns.entries+[{'entity': entity, }] -%}
        {%- endfor -%}   {{ ns.entries }}
    sort:
      method: none
    ll_context:
      group: sensor.temperatures_koelkasten
      name: Temperatuur
``` 

The same card where ll_context doesn't replicate to all the lower card levels. The only difference is that I start with an entities card on top level:
``` 
ll_key: test_card
ll_context:
  group: sensor.temperatures_koelkasten
  name: Temperatuur
type: entities
entities:
  - type: custom:collapsable-cards
    title_card:
      type: tile
      name: <%= context.name %>
      entity: <%= context.group %>
    cards:
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          template: >
            {% set ns=namespace(entries=[]) %}  {% set entities=state_attr('<%=
            context.group %>','entity_id') or [] %}  {%- for entity in entities
            -%}
              {%- set ns.entries=ns.entries+[{'entity': entity, }] -%}
            {%- endfor -%}   {{ ns.entries }}
        sort:
          method: none
      - type: custom:auto-entities
        card:
          type: history-graph
          hours_to_show: 48
        filter:
          template: >
            {% set ns=namespace(entries=[]) %}  {% set entities=state_attr('<%=
            context.group %>','entity_id') or [] %}  {%- for entity in entities
            -%}
              {%- set ns.entries=ns.entries+[{'entity': entity, }] -%}
            {%- endfor -%}   {{ ns.entries }}
        sort:
          method: none

```
