### ISSUE TITLE
context defaults from source template overwrite variables in target template cards

### ISSUE THREAD

**Issue by SanAndreaP** [daredoes/linked-lovelace-ui#42]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
2.2.6-beta

**Last working release (if known):**
2.2.5

**Browser and Operating System:**
Firefox 134.0 x64, Manjaro 6.12.4-1

**Description of problem:**
As the title says, the default values within the context variables of the source template card now overwrite all target template context variables.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
source template card:
```yaml
ll_key: socket-card
ll_context:
  entity: switch.x
  sensor: sensor.x_power
  color: r, g, b
type: vertical-stack
cards:
  - type: tile
    entity: <%= context.entity %>
    color: rgb(<%= context.color %>)
  - type: gauge
    entity: <%= context.sensor %>
```

expected target template card:
```yaml
ll_template: socket-card
ll_context:
  entity: switch.actual_switch_entity
  sensor: sensor.actual_switch_entity_power
  color: 255, 128, 128
type: vertical-stack
cards:
  - type: tile
    entity: switch.actual_switch_entity
    color: rgb(255, 128, 128)
  - type: gauge
    entity: sensor.actual_switch_entity_power
```

what is happening instead:
```yaml
ll_template: socket-card
ll_context:
  entity: switch.x
  sensor: sensor.x_power
  color: r, g, b
type: vertical-stack
cards:
  - type: tile
    entity: switch.x
    color: rgb(r, g, b)
  - type: gauge
    entity: sensor.x_power
```
